var sourcesIndex = JSON.parse('{\
"allocator":["",[],["bitmap.rs","buddy.rs","lib.rs","slab.rs"]],\
"arm_gic":["",[],["gic_v2.rs","lib.rs"]],\
"axalloc":["",[],["lib.rs","page.rs"]],\
"axconfig":["",[],["config_qemu_virt_riscv.rs","lib.rs"]],\
"axdisplay":["",[],["lib.rs"]],\
"axdriver":["",[],["lib.rs","virtio.rs"]],\
"axerrno":["",[],["lib.rs"]],\
"axfs":["",[["api",[],["dir.rs","file.rs","mod.rs"]],["fs",[],["fatfs.rs","mod.rs"]]],["dev.rs","fops.rs","lib.rs","root.rs"]],\
"axfs_devfs":["",[],["dir.rs","lib.rs","null.rs","zero.rs"]],\
"axfs_vfs":["",[],["lib.rs","macros.rs","path.rs","structs.rs"]],\
"axhal":["",[["arch",[["x86_64",[],["context.rs","mod.rs"]]],["mod.rs"]],["platform",[["dummy",[],["mod.rs"]]],["mod.rs"]]],["cpu.rs","irq.rs","lib.rs","mem.rs","paging.rs","time.rs","trap.rs"]],\
"axio":["",[["buffered",[],["bufreader.rs","mod.rs"]]],["error.rs","impls.rs","lib.rs","prelude.rs"]],\
"axlog":["",[],["lib.rs"]],\
"axnet":["",[["smoltcp_impl",[],["listen_table.rs","mod.rs","tcp.rs"]]],["lib.rs"]],\
"axruntime":["",[],["lib.rs","mp.rs","trap.rs"]],\
"axsync":["",[],["lib.rs","mutex.rs"]],\
"axtask":["",[],["api.rs","lib.rs","run_queue.rs","task.rs","timers.rs","wait_queue.rs"]],\
"capability":["",[],["lib.rs"]],\
"crate_interface":["",[],["lib.rs"]],\
"driver_block":["",[],["lib.rs","ramdisk.rs"]],\
"driver_common":["",[],["lib.rs"]],\
"driver_display":["",[],["lib.rs"]],\
"driver_net":["",[],["lib.rs"]],\
"driver_virtio":["",[],["blk.rs","gpu.rs","lib.rs","net.rs"]],\
"handler_table":["",[],["lib.rs"]],\
"kernel_guard":["",[["arch",[],["mod.rs","x86.rs"]]],["lib.rs"]],\
"lazy_init":["",[],["lib.rs"]],\
"libax":["",[["cbindings",[],["ctypes_gen.rs","fs.rs","malloc.rs","mod.rs","utils.rs"]],["display",[],["mod.rs"]],["io",[],["mod.rs","stdio.rs"]],["net",[],["mod.rs","tcp.rs"]],["sync",[],["mod.rs"]]],["env.rs","fs.rs","lib.rs","rand.rs","task.rs","time.rs"]],\
"linked_list":["",[],["lib.rs","linked_list.rs","unsafe_list.rs"]],\
"memory_addr":["",[],["lib.rs"]],\
"page_table":["",[["arch",[],["aarch64.rs","mod.rs","riscv.rs","x86_64.rs"]]],["bits64.rs","lib.rs"]],\
"page_table_entry":["",[["arch",[],["aarch64.rs","mod.rs","riscv.rs","x86_64.rs"]]],["lib.rs"]],\
"percpu":["",[],["imp.rs","lib.rs"]],\
"percpu_macros":["",[],["lib.rs","naive.rs"]],\
"ratio":["",[],["lib.rs"]],\
"scheduler":["",[],["fifo.rs","lib.rs","round_robin.rs"]],\
"slab_allocator":["",[],["lib.rs","slab.rs"]],\
"spinlock":["",[],["base.rs","lib.rs"]],\
"timer_list":["",[],["lib.rs"]],\
"tuple_for_each":["",[],["lib.rs"]]\
}');
createSourceSidebar();
